### ISSUE TITLE
Problem with response time mesure

### ISSUE THREAD

**Issue by clembert** [Semiadmin/zbx-win-agent-ping#1]
The measurement of the response time goes back a lot of data, but they are only 1 ms or 0 ms. How can I get more precise results?

**Comment by Semiadmin** [comment]
Win32_PingStatus WMI class returns ResponseTime in ms (uint32) so there isn't a possibility to get more precision value. If you get 0 or 1 ms it means your response time is about 1 ms. The Zabbix standard icmppingsec item gets ping response time with precision 0.1 ms and returns 0.0001 in case of response time less than 0.1 ms and 0 in case of timeout. It suits for triggers but not so good for visualization because sometimes you hardly can tell 0 (timeout) from 0.0001 (good ping) in a graph. In my template 0 ms means response time less than 1 ms and a gap in a chart means timeout. For triggers, you may use items ping.status (ping loss) and response.time (high ping).

**Comment by clembert** [comment]
OK.
Thank you for your answer.
